-- Snowflake · ACDOCA · generated from column schema
CREATE OR REPLACE TABLE SAP_FI.ACDOCA (
  MANDT     VARCHAR(3) NOT NULL,
  RBUKRS    VARCHAR(4) NOT NULL,
  RYEAR     VARCHAR(4) NOT NULL,
  POPER     VARCHAR(3) NOT NULL,
  BELNR     VARCHAR(10) NOT NULL,
  WSL       NUMBER(23, 2),
  CONSTRAINT PK_ACDOCA PRIMARY KEY (MANDT, RBUKRS, RYEAR, POPER, BELNR)
)
CLUSTER BY (RYEAR, RBUKRS);