-- Snowflake · BKPF · generated from column schema
CREATE OR REPLACE TABLE SAP_FI.BKPF (
  MANDT     VARCHAR(3) NOT NULL,
  BUKRS     VARCHAR(4) NOT NULL,
  BELNR     VARCHAR(10) NOT NULL,
  GJAHR     VARCHAR(4) NOT NULL,
  BLART     VARCHAR(2),
  BLDAT     DATE,
  WAERS     VARCHAR(5),
  CONSTRAINT PK_BKPF PRIMARY KEY (MANDT, BUKRS, BELNR, GJAHR)
)
CLUSTER BY (GJAHR, BUKRS);