-- Snowflake · MARA · generated from column schema
CREATE OR REPLACE TABLE SAP_MM.MARA (
  MANDT     VARCHAR(3) NOT NULL,
  MATNR     VARCHAR(40) NOT NULL,
  ERSDA     DATE,
  ERNAM     VARCHAR(12),
  MTART     VARCHAR(4),
  MATKL     VARCHAR(9),
  BRGEW     NUMBER(13, 3),
  GEWEI     VARCHAR(3),
  CONSTRAINT PK_MARA PRIMARY KEY (MANDT, MATNR)
)
CLUSTER BY (MATNR);